### ISSUE TITLE
Crash during Setup

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/lttrs-android#118]
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
 	at rs.ltt.jmap.common.entity.Account.hasCapability(Account.java:54)
 	at rs.ltt.jmap.client.session.Session.lambda$getAccounts$1(Session.java:108)
 	at rs.ltt.jmap.client.session.Session$$ExternalSyntheticLambda0.apply(Unknown Source:4)
 	at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:221)
 	at com.google.common.collect.ForwardingCollection.size(ForwardingCollection.java:65)
 	at java.util.AbstractMap.size(AbstractMap.java:85)
 	at rs.ltt.android.ui.model.SetupViewModel.processAccounts(SetupViewModel.java:289)
 	at rs.ltt.android.ui.model.SetupViewModel.access$000(SetupViewModel.java:64)
 	at rs.ltt.android.ui.model.SetupViewModel$2.onSuccess(SetupViewModel.java:202)
 	at rs.ltt.android.ui.model.SetupViewModel$2.onSuccess(SetupViewModel.java:198)
 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1080)
 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:746)
 	at rs.ltt.jmap.client.util.SettableCallFuture.set(SettableCallFuture.java:40)
 	at rs.ltt.jmap.client.session.SessionClient$1.onResponse(SessionClient.java:126)
 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 	at java.lang.Thread.run(Thread.java:923)
```

* This shouldn’t crash
* This should lead to endless loading

**Comment by iNPUTmice** [comment]
Server response looked like this:
```json
{
  "username": "alpha@ltt.rs",
  "apiUrl": "/jmap/",
  "downloadUrl": "/jmap/download/{accountId}/{blobId}/{name}?accept={type}",
  "uploadUrl": "/jmap/upload/{accountId}/",
  "eventSourceUrl": "/jmap/eventsource/?types={types}&closeafter={closeafter}&ping={ping}",
  "state": "0",
  "capabilities": {
    "urn:ietf:params:jmap:core": {
      "maxSizeUpload": 1073741824,
      "maxConcurrentUpload": 5,
      "maxSizeRequest": 10485760,
      "maxConcurrentRequests": 5,
      "maxCallsInRequest": 50,
      "maxObjectsInGet": 4096,
      "maxObjectsInSet": 4096,
      "collationAlgorithms": []
    },
    "https://cyrusimap.org/ns/jmap/quota": {},
    "https://cyrusimap.org/ns/jmap/performance": {},
    "https://cyrusimap.org/ns/jmap/debug": {},
    "https://cyrusimap.org/ns/jmap/blob": {
      "maxSizeBlobSet": 4096
    },
    "https://cyrusimap.org/ns/jmap/usercounters": {},
    "urn:ietf:params:jmap:mail": {},
    "https://cyrusimap.org/ns/jmap/mail": {},
    "urn:ietf:params:jmap:submission": {},
    "urn:ietf:params:jmap:vacationresponse": {},
    "urn:ietf:params:jmap:mdn": {},
    "https://cyrusimap.org/ns/jmap/contacts": {},
    "https://cyrusimap.org/ns/jmap/calendars": {},
    "https://cyrusimap.org/ns/jmap/backup": {},
    "https://cyrusimap.org/ns/jmap/sieve": {},
    "urn:ietf:params:jmap:websocket": {
      "webSocketUrl": "wss:/jmap/ws/",
      "supportsWebSocketPush": false
    }
  },
  "accounts": {
    "alpha@ltt.rs": {
      "name": "alpha@ltt.rs",
      "isPrimary": true,
      "isPersonal": true,
      "isReadOnly": false,
      "accountCapabilities": null
    }
  },
  "primaryAccounts": {
    "urn:ietf:params:jmap:mail": "alpha@ltt.rs",
    "urn:ietf:params:jmap:submission": "alpha@ltt.rs",
    "https://cyrusimap.org/ns/jmap/contacts": "alpha@ltt.rs",
    "https://cyrusimap.org/ns/jmap/calendars": "alpha@ltt.rs",
    "https://cyrusimap.org/ns/jmap/backup": "alpha@ltt.rs",
    "urn:ietf:params:jmap:vacationresponse": "alpha@ltt.rs",
    "https://cyrusimap.org/ns/jmap/sieve": "alpha@ltt.rs"
  }
}
```
