### ISSUE TITLE
NPE on some e-mails

### ISSUE THREAD

**Issue by wiktor-k** [iNPUTmice/lttrs-android#7]
Hello,

I got the following NPE:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
 	at rs.ltt.android.entity.EmailAddress.getName(EmailAddress.java:31)
 	at rs.ltt.android.entity.FullEmail.getTo(FullEmail.java:92)
	at rs.ltt.android.databinding.EmailItemBindingImpl.executeBindings(EmailItemBindingImpl.java:160)
```

on several e-mails, it seems the `To` header contains `undisclosed-recipients:;`:

```
From:   David Anderson <cw4763558@gmail.com>
Date:   Sun, 22 Dec 2019 07:15:33 +0100
Message-ID: <CABFr_RXwkyd4_x3GispJkT8K=pyC1XXk2whdOSJ_U2=s--R6hg@mail.gmail.com>
Subject: Approved to me that you got my mail.
To:     undisclosed-recipients:;
Content-Type: text/plain; charset="UTF-8"
Sender: linux-kernel-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-kernel.vger.kernel.org>
X-Mailing-List: linux-kernel@vger.kernel.org
```

That's how the JMAP endpoint represents the e-mail:

```
{
  "from": [
    {
      "name": "David Anderson",
      "email": "cw4763558@gmail.com"
    }
  ],
  "mailboxIds": {
    "0e384f2f-837d-4389-b6a9-f321ccca193d": true
  },
  "subject": "Approved to me that you got my mail.",
  "size": 10198,
  "snoozed": null,
  "keywords": {
    "$ismailinglist": true,
    "$seen": true,
    "$flagged": true,
    "$x-me-annot-2": true
  },
  "id": "M2256f8c460e77d88a02b9dd6",
  "spamScore": 0.8,
  "threadId": "Tb3a521256b8e769a",
  "receivedAt": "2019-12-22T06:15:39Z",
  "trustedSender": null,
  "preview": "-- \n*Dear Friend,*\n*I am David Anderson. I work as a procurement assistant. I got your\ncontact details in my search for a reliable and neutral company or\nindividual to partner with me in area of investment. I need your",
  "to": [
    {
      "email": null,
      "name": "undisclosed-recipients"
    },
    {
      "email": null,
      "name": null
    }
  ],
  "removedDates": {},
  "hasAttachment": false
}
```

Note one too many `null`s in `to` field.

**Comment by wiktor-k** [comment]
I think we can close this one. This is clearly triggered by a bug in Cyrus, not Ltt.rs.
